export type EnglishTenseTheory = {
  key: string;
  title: string;
  formula: string;
  purpose: string;
  signalWords: string;
  examples: Array<{ english: string; russian: string }>;
  mistakes: string[];
};

const rows: EnglishTenseTheory[] = [
  { key: "present-simple", title: "Present Simple", formula: "I/you/we/they work; he/she/it works", purpose: "Привычки, факты, расписания и действия, которые повторяются регулярно.", signalWords: "usually, often, every day, on Mondays", examples: [{ english: "She studies English every evening.", russian: "Она изучает английский каждый вечер." }, { english: "Water boils at 100°C.", russian: "Вода кипит при 100 °C." }], mistakes: ["Не добавляйте -s после I, you, we и they.", "В вопросах и отрицаниях после does используйте начальную форму: Does she work?"] },
  { key: "present-continuous", title: "Present Continuous", formula: "am/is/are + verb-ing", purpose: "Действие происходит сейчас или носит временный характер в текущий период.", signalWords: "now, at the moment, today, this week", examples: [{ english: "They are preparing dinner now.", russian: "Они сейчас готовят ужин." }, { english: "I am working from home this week.", russian: "На этой неделе я временно работаю из дома." }], mistakes: ["Нельзя убрать to be: I working неверно, нужно I am working.", "После am/is/are нужна форма с -ing."] },
  { key: "present-perfect", title: "Present Perfect", formula: "have/has + past participle", purpose: "Прошлый опыт или действие с результатом, важным сейчас; точный момент не является главным.", signalWords: "already, just, ever, never, yet, so far", examples: [{ english: "We have already finished the task.", russian: "Мы уже закончили задание." }, { english: "He has never visited Spain.", russian: "Он никогда не посещал Испанию." }], mistakes: ["С he, she и it используйте has.", "Не ставьте конкретное законченное время вроде yesterday с Present Perfect."] },
  { key: "present-perfect-continuous", title: "Present Perfect Continuous", formula: "have/has been + verb-ing", purpose: "Действие началось раньше и продолжается сейчас или только что закончилось; важна длительность.", signalWords: "for, since, all morning, lately", examples: [{ english: "She has been reading for an hour.", russian: "Она читает уже час." }, { english: "They have been waiting since noon.", russian: "Они ждут с полудня." }], mistakes: ["После have/has нужны сразу been и форма -ing.", "For обозначает период, since — начальный момент."] },
  { key: "past-simple", title: "Past Simple", formula: "worked; went; did not work; Did you work?", purpose: "Завершённое действие в прошлом, обычно с известным временем.", signalWords: "yesterday, last week, ago, in 2024", examples: [{ english: "I visited my aunt last weekend.", russian: "Я навещал тётю в прошлые выходные." }, { english: "They built the model yesterday.", russian: "Они построили модель вчера." }], mistakes: ["После did/did not используйте начальную форму: Did you go?", "У неправильных глаголов нужно запомнить вторую форму."] },
  { key: "past-continuous", title: "Past Continuous", formula: "was/were + verb-ing", purpose: "Процесс в определённый момент прошлого или фон, который был прерван другим событием.", signalWords: "at 7 yesterday, while, when", examples: [{ english: "I was cooking when you called.", russian: "Я готовил, когда ты позвонил." }, { english: "They were studying at eight.", russian: "Они занимались в восемь часов." }], mistakes: ["С I, he, she и it используется was, с you, we и they — were.", "Время показывает процесс, а не просто факт завершения."] },
  { key: "past-perfect", title: "Past Perfect", formula: "had + past participle", purpose: "Действие, которое произошло раньше другого действия или момента в прошлом.", signalWords: "before, by the time, already", examples: [{ english: "The film had started before we arrived.", russian: "Фильм уже начался до того, как мы приехали." }, { english: "She had finished the work by six.", russian: "Она закончила работу к шести." }], mistakes: ["Had одинаково для всех лиц.", "Сначала определите более раннее действие, а затем поставьте его в Past Perfect."] },
  { key: "past-perfect-continuous", title: "Past Perfect Continuous", formula: "had been + verb-ing", purpose: "Длительный процесс, который продолжался до определённого момента в прошлом.", signalWords: "for, since, before, by the time", examples: [{ english: "He had been working for three hours before lunch.", russian: "Он работал три часа до обеда." }, { english: "They had been waiting since morning.", russian: "Они ждали с утра." }], mistakes: ["В конструкции обязательно есть had been.", "Это время выбирают, когда важна длительность до прошлого момента, а не только результат."] },
  { key: "future-simple", title: "Future Simple", formula: "will + base verb", purpose: "Будущее действие, спонтанное решение, обещание или предположение.", signalWords: "tomorrow, soon, next week, I think", examples: [{ english: "I will call you tomorrow.", russian: "Я позвоню тебе завтра." }, { english: "I think she will pass the test.", russian: "Я думаю, она сдаст тест." }], mistakes: ["После will всегда идёт начальная форма глагола.", "Не добавляйте -s: he will work, а не he will works."] },
  { key: "future-continuous", title: "Future Continuous", formula: "will be + verb-ing", purpose: "Процесс, который будет идти в определённый момент будущего.", signalWords: "at this time tomorrow, at 8 next Friday, while", examples: [{ english: "At eight, I will be travelling home.", russian: "В восемь я буду ехать домой." }, { english: "They will be studying while we are away.", russian: "Они будут заниматься, пока нас не будет." }], mistakes: ["После will be нужна форма -ing.", "Указанный будущий момент должен пересекаться с процессом."] },
  { key: "future-perfect", title: "Future Perfect", formula: "will have + past participle", purpose: "Действие завершится к определённому моменту в будущем.", signalWords: "by Friday, by the end of, before", examples: [{ english: "She will have finished by Friday.", russian: "Она закончит к пятнице." }, { english: "We will have built the model by noon.", russian: "Мы построим модель к полудню." }], mistakes: ["После will have нужна третья форма глагола.", "By указывает крайний будущий момент, к которому будет готов результат."] },
  { key: "future-perfect-continuous", title: "Future Perfect Continuous", formula: "will have been + verb-ing", purpose: "Показывает, сколько будет длиться действие к моменту в будущем.", signalWords: "for ... by, since ... by, by the time", examples: [{ english: "By June, I will have been studying for a year.", russian: "К июню я буду изучать это уже год." }, { english: "By noon, they will have been working for four hours.", russian: "К полудню они будут работать уже четыре часа." }], mistakes: ["Не путайте с Future Perfect: здесь важна длительность, поэтому нужна форма -ing.", "В конструкции сохраняются все три части: will, have been и смысловой глагол с -ing."] },
];

export const getEnglishTenseTheory = (topicTitle: string) => {
  const normalized = topicTitle.trim().toLowerCase();
  return rows.find((item) => item.title.toLowerCase() === normalized) ?? null;
};

export const isEnglishTenseTopic = (topicTitle: string) => Boolean(getEnglishTenseTheory(topicTitle));
